version: '3'
services:
  dev:
    build:
      context: .
    links:
      - db
    environment:
      RAILS_ENV:
      DB_HOST:
      DB_PORT:
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME:
      REDIS_HOST:
      REDIS_PORT:
      REDIS_DATABASE:

      BUNDLE_WITHOUT: production
    volumes:
      - ../..:/app
      - rubygems_cache:/usr/local/bundle

volumes:
  rubygems_cache:
