version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
    - 6.2.1
  - dependency-name: listen
    versions:
    - 3.5.0
    - 3.5.1
  - dependency-name: sentry-raven
    versions:
    - 3.1.2
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.1.3
    - 6.1.3.1
  - dependency-name: iodine
    versions:
    - 0.7.43
    - 0.7.44
  - dependency-name: jbuilder
    versions:
    - 2.11.2
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: activeadmin
    versions:
    - 2.9.0
  - dependency-name: web-console
    versions:
    - 4.1.0
  - dependency-name: uk_postcode
    versions:
    - 2.1.6
  - dependency-name: spring
    versions:
    - 2.1.1
  - dependency-name: dotenv-rails
    versions:
    - 2.7.6
