# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - develop
  tags:
    include:
    - v*

      
pr:
  autoCancel: true
  branches:
    include:
      - develop
      - feature/*

variables:
  application.name: 'et-admin'
  azure.subscription.endpoint: 'hmcts-pet'
  manual.branch.prefix: 'develop'


jobs:

  - job: BuildAndPushImageCI

    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')), ne(variables['Build.Reason'], 'Manual'))
    pool:
      name: hmcts-pet

    steps:
    - template: ./pipeline-steps/docker-build.yaml
      parameters:
        azureContainerRegistry: $(azure.container.registry)
        azureSubscriptionEndpoint: $(azure.subscription.endpoint)
        applicationName: $(application.name)


  - job: BuildAndPushImageRelease

    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      name: hmcts-pet

    steps:
    - template: ./pipeline-steps/docker-build-release.yaml
      parameters:
        azureContainerRegistry: $(azure.container.registry)
        azureSubscriptionEndpoint: $(azure.subscription.endpoint)
        applicationName: $(application.name)


  - job: BuildAndPushImageManual
  
    condition: eq(variables['Build.Reason'], 'Manual')
    pool:
      name: hmcts-pet

    steps:
    - template: ./pipeline-steps/docker-build-manual.yaml
      parameters:
        azureContainerRegistry: $(azure.container.registry)
        azureSubscriptionEndpoint: $(azure.subscription.endpoint)
        manualBranchPrefix: $(manual.branch.prefix)
        applicationName: $(application.name)
